### ISSUE TITLE
v1 backend migration

### ISSUE THREAD

**Issue by joschahenningsen** [TUM-Dev/Campus-Backend#7]
# Cronjobs
- [ ] `alarm` ⇒ #220 
- [x] `kino` (now `movies`) ⇒ #213 
- [x] `news` ⇒ #3, #4
- [x] `roomfinder` -> #215 
- [ ] `mensa` -> is this nessesary?

# Endpoints

This is a list of endpoints that should be served here (via rest and grpc):
Update Note (previously unused in the Android app ⇒ needs a discussion)
- [x] `GET /updatenote/:version` ⇒ #226

## Members/Users
- [ ] `POST /members/:lrz_id`

## notifications
- [ ] `GET /notifications`
- [ ] `GET /notifications/confirm/:notification_id`

## Device
- [ ] `POST /device/register`
- [ ] `GET /device/verifyKey`
- [ ] `POST /device/addGcmToken`
- [ ] `GET /device/uploaded/:lrz_id`

## Feedback
- [x] `POST /feedback` (merged with)
      `POST /feedback/:id/:image_nr` ⇒ #199 #228 

## Cafeterias 
- [ ] `GET /mensen`

## Kinos
- [x] `GET /kino/:last_id` ⇒ https://github.com/TUM-Dev/Campus-Backend/pull/213

## News
- [x] `GET /news/:last_news_id`  ⇒  #227
- [x] `GET /news/sources`
- [x] `GET /news/alert` ⇒ https://github.com/TUM-Dev/Campus-Backend/pull/219

# other endpoints

<details><summary>
Study Rooms (basically just a thin API-Wrapper around iris' api. Unclear if needed)
</summary><p>

- [ ] `GET /studyroom/list`

</p></details>

<details><summary>
Events And Tickets (currently unused ⇒ needs a discussion if this is needed)
</summary><p>

- [ ] `GET /event/list`
- [ ] `POST /event/ticket/my`
- [ ] `POST /event/ticket/:ticket_id`
- [ ] `GET /event/ticket//type/:event_id`
- [ ] `POST /event/ticket/reserve/multiple`
- [ ] `POST /event/ticket/payment/stripe/purchase/multiple`
- [ ] `POST /event/ticket/payment/stripe/ephemeralkey`
- [ ] `GET /event/ticket/status/:event_id`

</p></details>

<details><summary>
Offloaded to [NavigaTUM](https://github.com/TUM-Dev/NavigaTUM)
</summary><p>

## Opening Hours
- [ ] `GET /openingtimes/:language`
- [ ] `GET /locations/:location_id`
- [ ] `GET /barrierfree/contacts`
- [x] `GET /barrierfree/getBuilding2Gps`
- [x] `GET /barrierfree/nerby/:building_id`
- [x] `GET /barrierfree/listOfToilets`
- [x] `GET /barrierfree/listOfElevators`
- [ ] `GET /barrierfree/moreInformation`

</p></details>

**Comment by kmodexc** [comment]
Is openingtimes already migrated? I could not find it.

**Comment by kordianbruck** [comment]
Nope, that isn't being worked on yet.

**Comment by barisconur** [comment]
I am going to work on this task in the following weeks.

**Comment by barisconur** [comment]
Could you please give me some information about the migration? Is there a new api version and do we want to migrate these endpoints to the new one?

**Comment by kmodexc** [comment]
As i understand it, the old backend is private source.

**Comment by joschahenningsen** [comment]
Yes, we basically want to reimplement the current (closed source) api written in php. It might make sense to open source it to aid the progress here. Let's discuss this in the next team meeting (ping @kordianbruck) 

For further discussion I suggest meeting up about this on discord? @barisconur You're on the server already, right?

**Comment by barisconur** [comment]
@joschahenningsen I am not on the server. 
@kordianbruck When is the next team meeting?

**Comment by joschahenningsen** [comment]
@barisconur https://discord.gg/WSRzBkr7

Next meeting is scheduled for June, first @ 7PM

**Comment by barisconur** [comment]
> Yes, we basically want to reimplement the current (closed source) api written in php. It might make sense to open source it to aid the progress here. Let's discuss this in the next team meeting (ping @kordianbruck)

Hello again. I am going to work on this migration endpoints in the next 2 weeks. How can I access the source code of old api written in php.

**Comment by barisconur** [comment]
> > Yes, we basically want to reimplement the current (closed source) api written in php. It might make sense to open source it to aid the progress here. Let's discuss this in the next team meeting (ping @kordianbruck)
> 
> Hello again. I am going to work on this migration endpoints in the next 2 weeks. How can I access the source code of old api written in php.

Additionally, I created a new branch and I am trying to push it to the repo but it throws the error below.
`remote: Permission to TUM-Dev/Campus-Backend.git denied to barisconur.
fatal: unable to access 'https://github.com/TUM-Dev/Campus-Backend.git/': The requested URL returned error: 403
`

**Comment by tobiasjungmann** [comment]
You can not directly push to this repository if you are not a member. Instead you have to fork the repository, clone your fork (or set the git parameters in the version you have downloaded at the moment). Then you can push commits to your forked repo. These commits can then be added with a Pull Request from your forked repo to this repository.

**Comment by barisconur** [comment]
@tobiasjungmann  I am stuck at connecting my local database. I created a mariadb running container with:
`docker run --detach \
  --name mariadb-tum-backend \
  --env MARIADB_USER=root \
  --env MARIADB_ROOT_PASSWORD=example \
  --restart always \
  -p 3306:3306 \
  --volume "$(pwd)"/init.sql:/init.sql \
  mariadb:latest --init-file /init.sql`

I am able to connect it via DataGrip but I am not sure how to connect it in main.go. I tried: // main.go line 49-50
`		// conn = sqlite.Open("test.db")
		conn = mysql.Open("jdbc:mariadb://localhost:3306")`

**Comment by joschahenningsen** [comment]
@barisconur no need to modify the code. To connect to the local mariadb you have to add the database connection string (`root:example@tcp(localhost:3306)/tca-portal?charset=utf8mb4&parseTime=True&loc=Local`) to your environment variables like this:

![image](https://user-images.githubusercontent.com/44805696/169895585-c03b5e81-fc94-4ca2-a8e5-19a75f314d55.png)
![image](https://user-images.githubusercontent.com/44805696/169895691-1a561bf5-e04a-468d-b356-36f83e114dcc.png)
![image](https://user-images.githubusercontent.com/44805696/169895931-33a6570a-91aa-40dd-9bac-a16cbdbadc5b.png)

**Comment by barisconur** [comment]
> @barisconur no need to modify the code. To connect to the local mariadb you have to add the database connection string (`root:example@tcp(localhost:3306)/tca-portal?charset=utf8mb4&parseTime=True&loc=Local`) to your environment variables like this:
> 
> ![image](https://user-images.githubusercontent.com/44805696/169895585-c03b5e81-fc94-4ca2-a8e5-19a75f314d55.png) ![image](https://user-images.githubusercontent.com/44805696/169895691-1a561bf5-e04a-468d-b356-36f83e114dcc.png) ![image](https://user-images.githubusercontent.com/44805696/169895931-33a6570a-91aa-40dd-9bac-a16cbdbadc5b.png)

Hello,
It throws this error:
![image](https://user-images.githubusercontent.com/25527682/169899728-f20bdac1-c2a9-47ea-9867-3ddea7ec97e7.png)

I also tried with:
`root:example@tcp(localhost:3306)/mariadb-tum-backend?charset=utf8mb4&parseTime=True&loc=Local`

I changed tca_portal to mariadb-tum-backend.

**Comment by joschahenningsen** [comment]
Not sure if you successfully imported the database schema. If not, open the database connection in dataGrip, create a new query console, run `CREATE DATABASE tca-portal;` and then run this script on the database: https://raw.githubusercontent.com/TUM-Dev/Campus-Backend/db-models/model/souce-schema.sql

**Comment by barisconur** [comment]
> https://raw.githubusercontent.com/TUM-Dev/Campus-Backend/db-models/model/souce-schema.sql

Thanks. But it gives sql syntax error for "CREATE DATABASE tca-portal;". So I changed it to "tca_portal". But then the script threw some errors afterwards.
<img width="882" alt="image" src="https://user-images.githubusercontent.com/25527682/169903566-bf11c941-7784-4b84-bc7d-3670ddc3f3ac.png">
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/25527682/169903646-d99d2267-316a-4cb0-ad83-5de7ff5cd2a8.png">
